import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import MainSection from '@/components/MainSection'
import Step1Function from '@/components/Step1Section'
import Step2Function from '@/components/Step2Section'
import Step3Function from '@/components/Step3Section'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Repair Man</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='d-flex flex-column'>
      <MainSection />
      <Step1Function />
      <Step2Function />
      <Step3Function />
      </div>
    </>
  )
}
